# Generated by Django 5.2.7 on 2026-01-24 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KhaltiTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pidx', models.CharField(help_text='Unique identifier from Khalti', max_length=255, unique=True)),
                ('transaction_id', models.CharField(blank=True, help_text="Khalti's unique transaction ID", max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in Paisa', max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Refunded', 'Refunded'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='khalti_payments', to='organizer.ticketsale')),
            ],
        ),
    ]
