# Generated by Django 5.2.7 on 2025-11-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('link', models.URLField()),
                ('source', models.CharField(max_length=50)),
                ('published', models.DateTimeField()),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
