# Generated by Django 5.2.7 on 2026-02-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='SportsBoard', max_length=150)),
                ('support_email', models.EmailField(default='support@sportsboard.com', max_length=254)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('commission', models.PositiveIntegerField(default=10)),
                ('max_duration', models.PositiveIntegerField(default=24)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
