# Generated by Django 5.2.7 on 2026-02-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='admin_session_timeout',
            field=models.PositiveIntegerField(default=120),
        ),
    ]
