# Generated by Django 5.2.7 on 2026-02-16 16:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ATHLETE', 'Athlete'), ('ORGANIZER', 'Organizer'), ('ADMIN', 'Admin')], default='ATHLETE', max_length=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('citizenship_no', models.CharField(blank=True, help_text='Required for Organizers', max_length=50, null=True)),
                ('id_front', models.ImageField(blank=True, null=True, upload_to='kyc/ids/')),
                ('id_back', models.ImageField(blank=True, null=True, upload_to='kyc/ids/')),
                ('phone_number', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit Nepal phone number.', regex='^9\\d{9}$')])),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
