# Generated by Django 5.2.7 on 2026-02-16 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('LIVE', 'Live'), ('UPCOMING', 'Upcoming'), ('COMPLETED', 'Completed')], default='UPCOMING', max_length=10)),
                ('game_type', models.CharField(choices=[('MULTI', 'Sports Week 🏆'), ('FOOTBALL', 'Football ⚽'), ('BASKETBALL', 'Basketball 🏀'), ('BADMINTON', 'Badminton 🏸'), ('VOLLEYBALL', 'Volleyball 🏐'), ('CRICKET', 'Cricket 🏏'), ('OTHER', 'Others')], default='FOOTBALL', max_length=20)),
                ('game_type_other', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='event_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KhaltiTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pidx', models.CharField(help_text='Khalti Payment ID', max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='INITIATED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('MULTI', 'Sports Week 🏆'), ('FOOTBALL', 'Football ⚽'), ('BASKETBALL', 'Basketball 🏀'), ('BADMINTON', 'Badminton 🏸'), ('VOLLEYBALL', 'Volleyball 🏐'), ('CRICKET', 'Cricket 🏏'), ('OTHER', 'Others')], default='FOOTBALL', max_length=20)),
                ('team_a', models.CharField(max_length=100, verbose_name='Team A / Player 1')),
                ('team_b', models.CharField(max_length=100, verbose_name='Team B / Player 2')),
                ('match_time', models.DateTimeField()),
                ('venue', models.CharField(blank=True, max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='organizer.event')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerSelectionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(blank=True, max_length=255)),
                ('sports', models.CharField(blank=True, max_length=100)),
                ('level', models.CharField(choices=[('district', 'District'), ('province', 'Province'), ('national', 'National'), ('none', 'None')], max_length=20)),
                ('address', models.CharField(blank=True, help_text='Event Venue Address', max_length=255)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('temporary_address', models.CharField(blank=True, max_length=255)),
                ('permanent_address', models.CharField(blank=True, max_length=255)),
                ('guardian_name', models.CharField(blank=True, max_length=100)),
                ('guardian_relation', models.CharField(blank=True, max_length=50)),
                ('guardian_phone', models.CharField(blank=True, max_length=15)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5, null=True)),
                ('experience_level', models.CharField(choices=[('beginner', 'Beginner (School/College)'), ('club', 'Club Level'), ('district', 'District Level'), ('provincial', 'Provincial Level'), ('national', 'National/Professional')], default='beginner', max_length=20)),
                ('previous_experience_details', models.TextField(blank=True, help_text='List major tournaments or clubs')),
                ('medical_conditions', models.BooleanField(default=False, help_text='Do you have any medical conditions?')),
                ('medical_details', models.TextField(blank=True, help_text='If yes, please specify')),
                ('citizenship_number', models.CharField(blank=True, max_length=50, null=True)),
                ('certificates', models.FileField(blank=True, null=True, upload_to='documents/certs/')),
                ('citizenship', models.FileField(blank=True, null=True, upload_to='documents/citizenship/')),
                ('is_published', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration_forms', to='organizer.event')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_code', models.CharField(max_length=50, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('bought_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_ticket', to='organizer.khaltitransaction')),
            ],
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., VIP, Standard', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_quantity', models.IntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_tiers', to='organizer.event')),
            ],
        ),
        migrations.AddField(
            model_name='khaltitransaction',
            name='ticket_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizer.tickettype'),
        ),
    ]
