# Generated by Django 5.2.7 on 2026-02-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsale',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
