# Generated by Django 5.2.7 on 2025-11-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='game_type',
            field=models.CharField(choices=[('FOOTBALL', 'Football ⚽'), ('BASKETBALL', 'Basketball 🏀'), ('BADMINTON', 'Badminton 🏸'), ('VOLLEYBALL', 'Volleyball 🏐'), ('KABADDI', 'Kabaddi'), ('CRICKET', 'Cricket 🏏'), ('FUTSAL', 'Futsal'), ('OTHER', 'Others')], default='FOOTBALL', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='game_type_other',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Specify Other Game'),
        ),
        migrations.AddField(
            model_name='event',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='event_photos/'),
        ),
    ]
