# Generated by Django 5.2.7 on 2026-01-24 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_ticketsale_buyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickettype',
            name='match',
        ),
        migrations.AddField(
            model_name='tickettype',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_tiers', to='organizer.event'),
            preserve_default=False,
        ),
    ]
