# Generated by Django 5.2.7 on 2026-02-19 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_ticketsale_checked_in_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(blank=True, max_length=255)),
                ('organization_logo', models.ImageField(blank=True, null=True, upload_to='org_logos/')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('bio', models.TextField(blank=True, help_text='Short description of your organization/club.')),
                ('enable_scanner_sound', models.BooleanField(default=True, help_text='Play a beep sound on successful scan.')),
                ('auto_submit_scan', models.BooleanField(default=True, help_text='Automatically submit the form after a QR code is detected.')),
                ('khalti_merchant_id', models.CharField(blank=True, help_text='Your Khalti Business ID for receiving payments.', max_length=100)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Optional tax to add to ticket prices.', max_digits=5)),
                ('email_notifications', models.BooleanField(default=True)),
                ('daily_summary_report', models.BooleanField(default=False, help_text='Receive a daily PDF summary of registrations.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
