# # Generated by Django 5.2.7 on 2025-11-23 12:57
#
# import django.db.models.deletion
# from django.conf import settings
# from django.db import migrations, models
#
#
# class Migration(migrations.Migration):
#
#     dependencies = [
#         ('organizer', '0003_tickettype'),
#         migrations.swappable_dependency(settings.AUTH_USER_MODEL),
#     ]
#
#     operations = [
#         migrations.AlterUniqueTogether(
#             name='application',
#             unique_together={('event', 'user')},
#         ),
#         migrations.AddField(
#             model_name='application',
#             name='dynamic_responses',
#             field=models.JSONField(default=dict, help_text='Stores answers to custom form fields as JSON.'),
#         ),
#         migrations.AddField(
#             model_name='application',
#             name='user',
#             field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
#             preserve_default=False,
#         ),
#         migrations.AlterField(
#             model_name='application',
#             name='event',
#             field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='organizer.event'),
#         ),
#         migrations.CreateModel(
#             name='SelectionForm',
#             fields=[
#                 ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                 ('is_active', models.BooleanField(default=True)),
#                 ('event', models.OneToOneField(help_text='The event this player selection form is for.', on_delete=django.db.models.deletion.CASCADE, related_name='selection_form', to='organizer.event')),
#             ],
#             options={
#                 'verbose_name': 'Selection Form',
#                 'verbose_name_plural': 'Selection Forms',
#             },
#         ),
#         migrations.CreateModel(
#             name='FormField',
#             fields=[
#                 ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                 ('label', models.CharField(max_length=255)),
#                 ('field_type', models.CharField(choices=[('TEXT', 'Text Input (Short Answer)'), ('TEXTAREA', 'Text Area (Long Answer)'), ('NUMBER', 'Number Input'), ('CHOICE', 'Dropdown / Select (Must specify options)'), ('CHECKBOX', 'Checkbox (Yes/No)')], max_length=10)),
#                 ('is_required', models.BooleanField(default=True)),
#                 ('options', models.TextField(blank=True, help_text='Comma-separated options for Choice fields (e.g., Option 1, Option 2)', null=True)),
#                 ('order', models.IntegerField(default=0)),
#                 ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='organizer.selectionform')),
#             ],
#             options={
#                 'verbose_name': 'Form Field',
#                 'verbose_name_plural': 'Form Fields',
#                 'ordering': ['order'],
#             },
#         ),
#         migrations.RemoveField(
#             model_name='application',
#             name='applicant_name',
#         ),
#     ]

# Generated by Django 5.2.7 on 2025-11-23 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('organizer', '0003_tickettype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. Remove the old field (applicant_name)
        migrations.RemoveField(
            model_name='application',
            name='applicant_name',
        ),

        # 2. Add the new field (user) - MUST happen before AlterUniqueTogether
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='applications',
                                    to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),

        # 3. Add the JSON field (dynamic_responses)
        migrations.AddField(
            model_name='application',
            name='dynamic_responses',
            field=models.JSONField(default=dict, help_text='Stores answers to custom form fields as JSON.'),
        ),

        # 4. Alter the foreign key field (event)
        migrations.AlterField(
            model_name='application',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications',
                                    to='organizer.event'),
        ),

        # 5. Apply the unique constraint (uses 'user', so must be after step 2)
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('event', 'user')},
        ),

        # 6. Create the new models (SelectionForm and FormField)
        migrations.CreateModel(
            name='SelectionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('event', models.OneToOneField(help_text='The event this player selection form is for.',
                                               on_delete=django.db.models.deletion.CASCADE,
                                               related_name='selection_form', to='organizer.event')),
            ],
            options={
                'verbose_name': 'Selection Form',
                'verbose_name_plural': 'Selection Forms',
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(
                    choices=[('TEXT', 'Text Input (Short Answer)'), ('TEXTAREA', 'Text Area (Long Answer)'),
                             ('NUMBER', 'Number Input'), ('CHOICE', 'Dropdown / Select (Must specify options)'),
                             ('CHECKBOX', 'Checkbox (Yes/No)')], max_length=10)),
                ('is_required', models.BooleanField(default=True)),
                ('options', models.TextField(blank=True,
                                             help_text='Comma-separated options for Choice fields (e.g., Option 1, Option 2)',
                                             null=True)),
                ('order', models.IntegerField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields',
                                           to='organizer.selectionform')),
            ],
            options={
                'verbose_name': 'Form Field',
                'verbose_name_plural': 'Form Fields',
                'ordering': ['order'],
            },
        ),
    ]