# Generated by Django 5.2.7 on 2026-01-24 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0003_remove_tickettype_match_tickettype_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerselectionform',
            name='transaction',
        ),
        migrations.AddField(
            model_name='playerselectionform',
            name='address',
            field=models.CharField(blank=True, help_text='Event Venue Address', max_length=255),
        ),
        migrations.AddField(
            model_name='playerselectionform',
            name='certificates',
            field=models.FileField(blank=True, null=True, upload_to='documents/certs/'),
        ),
        migrations.AddField(
            model_name='playerselectionform',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='playerselectionform',
            name='event_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='playerselectionform',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='playerselectionform',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='playerselectionform',
            name='guardian_relation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='playerselectionform',
            name='organizer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerselectionform',
            name='permanent_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='playerselectionform',
            name='sports',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='playerselectionform',
            name='temporary_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='playerselectionform',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration_forms', to='organizer.event'),
        ),
        migrations.AlterField(
            model_name='playerselectionform',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
