# Generated by Django 5.2.7 on 2026-02-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0004_organizerfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizerprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizerprofile',
            name='verification_status',
            field=models.CharField(choices=[('none', 'Not Submitted'), ('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='none', max_length=20),
        ),
    ]
