# Generated by Django 5.2.7 on 2026-02-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0005_organizerprofile_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizerprofile',
            name='address',
            field=models.CharField(blank=True, help_text='Full address of your organization', max_length=255),
        ),
        migrations.AddField(
            model_name='organizerprofile',
            name='certificate',
            field=models.FileField(blank=True, help_text='Upload your registration certificate or citizenship.', null=True, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='organizerprofile',
            name='organization_logo',
            field=models.ImageField(blank=True, help_text='This acts as your profile photo.', null=True, upload_to='org_logos/'),
        ),
    ]
