# Generated by Django 5.2.7 on 2026-02-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0006_organizerprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerselectionform',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='Form closes after this date', null=True),
        ),
    ]
