# Generated by Django 5.2.7 on 2025-12-15 13:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0006_alter_application_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectionform',
            name='event',
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='application',
            name='applicant_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizer.event'),
        ),
        migrations.DeleteModel(
            name='FormField',
        ),
        migrations.DeleteModel(
            name='SelectionForm',
        ),
        migrations.RemoveField(
            model_name='application',
            name='dynamic_responses',
        ),
        migrations.RemoveField(
            model_name='application',
            name='user',
        ),
    ]
