# Generated by Django 5.2.7 on 2025-12-23 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0007_remove_selectionform_event_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerSelectionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=False)),
                ('event_name', models.CharField(max_length=50)),
                ('sports', models.CharField(max_length=30)),
                ('level', models.CharField(choices=[('district', 'District Level'), ('province', 'Province Level'), ('national', 'National Level'), ('none', 'None')], max_length=20)),
                ('address', models.CharField(max_length=150)),
                ('full_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('age', models.CharField(max_length=2)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('temporary_address', models.CharField(max_length=150)),
                ('permanent_address', models.CharField(max_length=150)),
                ('guardian_name', models.CharField(max_length=150)),
                ('guardian_relation', models.CharField(max_length=100)),
                ('guardian_phone', models.CharField(max_length=15)),
                ('citizenship', models.FileField(upload_to='documents/citizenship/')),
                ('certificates', models.FileField(blank=True, upload_to='documents/certificates/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('selected', 'Selected'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
