# Generated by Django 5.2.7 on 2025-12-26 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0007_remove_selectionform_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('FOOTBALL', 'Football ⚽'), ('BASKETBALL', 'Basketball 🏀'), ('BADMINTON', 'Badminton 🏸'), ('VOLLEYBALL', 'Volleyball 🏐'), ('KABADDI', 'Kabaddi'), ('CRICKET', 'Cricket 🏏'), ('FUTSAL', 'Futsal'), ('OTHER', 'Others')], max_length=20)),
                ('team_a', models.CharField(max_length=100, verbose_name='Team A / Player 1')),
                ('team_b', models.CharField(max_length=100, verbose_name='Team B / Player 2')),
                ('match_time', models.DateTimeField()),
                ('venue', models.CharField(blank=True, max_length=100)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='organizer.event')),
            ],
        ),
    ]
