# Generated by Django 5.2.7 on 2025-12-26 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0008_match'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsale',
            name='buyer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticketsale',
            name='ticket_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizer.tickettype'),
        ),
    ]
