# Generated by Django 5.2.7 on 2025-12-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0008_playerselectionform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerselectionform',
            name='age',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='playerselectionform',
            name='citizenship',
            field=models.FileField(blank=True, null=True, upload_to='documents/citizenship/'),
        ),
        migrations.AlterField(
            model_name='playerselectionform',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerselectionform',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='playerselectionform',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='playerselectionform',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='playerselectionform',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='playerselectionform',
            name='permanent_address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='playerselectionform',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='playerselectionform',
            name='temporary_address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
