# Generated by Django 5.2.7 on 2025-12-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0009_ticketsale_buyer_ticketsale_ticket_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='game_type',
            field=models.CharField(choices=[('MULTI', 'Multi-Sport / Sports Week 🏆'), ('FOOTBALL', 'Football ⚽'), ('BASKETBALL', 'Basketball 🏀'), ('BADMINTON', 'Badminton 🏸'), ('VOLLEYBALL', 'Volleyball 🏐'), ('KABADDI', 'Kabaddi'), ('CRICKET', 'Cricket 🏏'), ('FUTSAL', 'Futsal'), ('OTHER', 'Others')], default='FOOTBALL', max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='game_type',
            field=models.CharField(choices=[('MULTI', 'Multi-Sport / Sports Week 🏆'), ('FOOTBALL', 'Football ⚽'), ('BASKETBALL', 'Basketball 🏀'), ('BADMINTON', 'Badminton 🏸'), ('VOLLEYBALL', 'Volleyball 🏐'), ('KABADDI', 'Kabaddi'), ('CRICKET', 'Cricket 🏏'), ('FUTSAL', 'Futsal'), ('OTHER', 'Others')], max_length=20),
        ),
    ]
