# Generated by Django 5.2.7 on 2025-12-26 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0009_alter_playerselectionform_age_and_more'),
        ('organizer', '0010_alter_event_game_type_alter_match_game_type'),
    ]

    operations = [
    ]
