# Generated by Django 5.2.7 on 2025-12-31 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0011_merge_20251226_2112'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerselectionform',
            name='certificates',
            field=models.FileField(blank=True, null=True, upload_to='documents/certificates/'),
        ),
        migrations.CreateModel(
            name='TrialSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('age', models.CharField(max_length=2)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('temporary_address', models.CharField(max_length=150)),
                ('permanent_address', models.CharField(max_length=150)),
                ('guardian_name', models.CharField(max_length=150)),
                ('guardian_relation', models.CharField(max_length=100)),
                ('guardian_phone', models.CharField(max_length=15)),
                ('citizenship', models.FileField(upload_to='submissions/citizenship/')),
                ('certificates', models.FileField(upload_to='submissions/certificates/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('is_notified', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('trial_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='organizer.playerselectionform')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
