# Generated by Django 5.2.7 on 2026-01-14 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0012_alter_playerselectionform_certificates_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrialSubmission',
        ),
    ]
