# Generated by Django 5.2.7 on 2026-01-17 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0012_alter_playerselectionform_certificates_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='playerselectionform',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playerselectionform',
            name='parent_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='organizer.playerselectionform'),
        ),
        migrations.AlterField(
            model_name='playerselectionform',
            name='age',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='playerselectionform',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='playerselectionform',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='playerselectionform',
            name='guardian_relation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='playerselectionform',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_selection_forms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playerselectionform',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='playerselectionform',
            name='sports',
            field=models.CharField(choices=[('cricket', 'Cricket'), ('football', 'Football'), ('volleyball', 'Volleyball'), ('basketball', 'Basketball'), ('badminton', 'Badminton'), ('other', 'Other')], max_length=30),
        ),
        migrations.DeleteModel(
            name='TrialSubmission',
        ),
    ]
