# Generated by Django 5.2.7 on 2026-01-17 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0013_delete_trialsubmission'),
        ('organizer', '0013_playerselectionform_applicant_and_more'),
    ]

    operations = [
    ]
