# Generated by Django 5.2.7 on 2025-11-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('match_type', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('venue', models.CharField(max_length=200)),
                ('is_free', models.BooleanField(default=True)),
                ('tickets_available', models.BooleanField(default=False)),
                ('highlights', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='matches/')),
            ],
        ),
    ]
